### ISSUE TITLE
Issues with XC Number Signs

### ISSUE THREAD

**Issue by RileyCasper** [DragN0007/DragN-XC-Jumps#2]
There's a few issues
1 looks out of place
5 is backwards
![2023-12-31_16 03 09](https://github.com/DragN0007/DragN-XC-Jumps/assets/80489042/89d8daab-df0b-45c7-b1e8-70d9aec0f778)

**Comment by DragN0007** [comment]
Thank you for the picture! I'll thin out the 1 and switch my 5 back around. I'll be attempting to patch up some small issues tonight, those included. Thanks!
